# https://travis-ci.org/HearthSim/django-hearthstone
sudo: false
language: python

python: "3.6"

env:
  - TOXENV=py36-django111
  - TOXENV=py36-djangomaster
  - TOXENV=flake8

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox
