# https://travis-ci.org/HearthSim/django-hearthstone
sudo: false
language: python

python: "3.6"

env:
  - TOXENV=flake8

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
