# Generated by Django 2.0.3 on 2018-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("cards", "0002_auto_20180321_1313"),
	]

	operations = [
		migrations.AlterField(
			model_name="card",
			name="card_id",
			field=models.CharField(db_index=True, max_length=50, unique=True),
		),
		migrations.AlterField(
			model_name="card",
			name="dbf_id",
			field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
			preserve_default=False,
		),
	]
