# Generated by Django 2.0.6 on 2019-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_auto_20180412_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
