name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
        matrix:
            toxenv: [django32, django40, django41, django42, djangomain, flake8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools types-setuptools wheel
        pip install tox
    - name: Run tox
      env:
          TOXENV: ${{ matrix.toxenv }}
      run: tox
  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
        # required to authenticate for the PyPi upload below
        id-token: write
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
